### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by beeternity** [XiangchenYin/PE-YOLO#3]
Hello, thanks for your open source code, what device did you use to run this code? Even on a  Tesla V100(32GB) I still encounter this problem, I guess the PENet  is the culprit, I have no idea whether PENet was set requires_grad = False in training.

**Comment by liuQan** [comment]
dear , do you have the complete source code? Or write your own code

**Comment by beeternity** [comment]
Actually I tried to take your proposed module into my network, but I found this effect wasn't significant. All in all, thank you for your generous open-source!
