### ISSUE TITLE
输入数据类型与权重类型不同

### ISSUE THREAD

**Issue by YuchaoXu** [XiangchenYin/PE-YOLO#8]
输入是cpu类型数据，而训练权重是gpu类型数据。
在cpu上可以训练，但无法在gpu上训练。请问有人解决了吗？

**Comment by BYbirdy** [comment]
试试这样：

        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        a = a.to(device)

**Comment by YuchaoXu** [comment]
> 试试这样：
> 
> ```
>     device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
>     a = a.to(device)
> ```

请问你是用的yolo源码复现还是用的mmdetection，我将整个PENet加到网络的第一层，但我每修改一个地方device，都会继续报下面一个代码的device，无法将整个PENet移动到gpu上，也许将PENet拆开加入网络会有效果。请问你在源码上复现成功了吗

**Comment by BYbirdy** [comment]
我用的mmdetection，论文PENet就是一个数据增强，我只用了论文的LEA和DPM模块


?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiangchenYin/PE-YOLO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月15日(星期五) 晚上7:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiangchenYin/PE-YOLO] 输入数据类型与权重类型不同 (Issue #8)





  
试试这样：
     device = torch.device("cuda" if torch.cuda.is_available() else "cpu")     a = a.to(device)   
请问你是用的yolo源码复现还是用的mmdetection，我将整个PENet加到网络的第一层，但我每修改一个地方device，都会继续报下面一个代码的device，无法将整个PENet移动到gpu上，也许将PENet拆开加入网络会有效果。请问你在源码上复现成功了吗

**Comment by zsn1107** [comment]
请问如何将PENet加进mmdetection中的yolov3呢

**Comment by zsn1107** [comment]
> 输入是cpu类型数据，而训练权重是gpu类型数据。 在cpu上可以训练，但无法在gpu上训练。请问有人解决了吗？

你好，请问您解决了吗。我想单独训练PENet时也遇到了这个问题，可以向您请教吗?非常感谢。
