### ISSUE TITLE
PENet中的bug

### ISSUE THREAD

**Issue by YuchaoXu** [XiangchenYin/PE-YOLO#9]
![image](https://github.com/XiangchenYin/PE-YOLO/assets/142774033/7b6e1c5f-8090-451c-8b2b-2c72eb247e4c)
源代码是注释掉的部分，不加.detach（）会报错，请问要不要加呢

**Comment by mrwrui** [comment]
我是直接放在gpu上训练了

**Comment by YuchaoXu** [comment]
> 我是直接放在gpu上训练了

请问你是单独训练的PENet，还是接在yolov3上呢

**Comment by mrwrui** [comment]
> > 我是直接放在gpu上训练了
> 
> 请问你是单独训练的PENet，还是接在yolov3上呢

接在yolov3上训练的

**Comment by YuchaoXu** [comment]
> > > 我是直接放在gpu上训练了
> > 
> > 
> > 请问你是单独训练的PENet，还是接在yolov3上呢
> 
> 接在yolov3上训练的

直接在源码接还是用了论文里的mmdetection呢

**Comment by YuchaoXu** [comment]
> > > 我是直接放在gpu上训练了
> > 
> > 
> > 请问你是单独训练的PENet，还是接在yolov3上呢
> 
> 接在yolov3上训练的

请问能提供一下源码吗，

**Comment by YuchaoXu** [comment]
> > > > 我是直接放在gpu上训练了
> > > 
> > > 
> > > 请问你是单独训练的PENet，还是接在yolov3上呢
> > 
> > 
> > 接在yolov3上训练的
> 
> 直接在源码接还是用了论文里的mmdetection呢

如果可以的话邮箱交流xuyuchao0319@163.com

**Comment by zsn1107** [comment]
> > > > > 我是直接放在gpu上训练了
> > > > 
> > > > 
> > > > 请问你是单独训练的PENet，还是接在yolov3上呢
> > > 
> > > 
> > > 接在yolov3上训练的
> > 
> > 
> > 直接在源码接还是用了论文里的mmdetection呢
> 
> 如果可以的话邮箱交流[xuyuchao0319@163.com](mailto:xuyuchao0319@163.com)

> xuyuchao0319@163.com

请问复现成功了吗，可以向您请教问题吗
